wp360-rescue finished save/restore script

diff --git a/wp360-rescue/usr/share/initramfs-tools/scripts/local-premount/wp360-rescue b/wp360-rescue/usr/share/initramfs-tools/scripts/local-premount/wp360-rescue
--- a/wp360-rescue/usr/share/initramfs-tools/scripts/local-premount/wp360-rescue
+++ b/wp360-rescue/usr/share/initramfs-tools/scripts/local-premount/wp360-rescue
@@ -17,6 +17,53 @@ export MAC_ADDRESS="$(cut /sys/class/net/eth0/address -d: -f1-6 -O)"
 export BS=$((10*1024*1024))
 export ZSTD_COMP_LEVEL=9
 
+
+shutdown_guard()
+{
+  gpioset --bias=pull-down --drive=push-pull gpiochip0 24=1
+  sleep 0.005
+  gpioset --bias=pull-down --drive=push-pull gpiochip0 24=0
+}
+
+
+set_run_led()
+{
+  gpioset --bias=pull-up --drive=open-drain gpiochip0 17=$1
+}
+
+
+blink_led()
+{
+  case $1 in
+    0)
+      blink=1
+      steps=1
+      waiting=0
+      ;;
+    1|2|3|4|5|6|7|8|9)
+      blink=0.2
+      steps=$1
+      waiting=3
+      ;;
+    *)
+      echo "Usage: $0 <0|1|2|3|4|5|6|7|8|9>" >&2
+      return
+      ;;
+  esac
+  while true
+  do
+    for i in $(seq 1 $steps)
+    do
+      set_run_led 0
+      sleep $blink
+      set_run_led 1
+      sleep $blink
+    done
+    sleep $waiting
+  done
+}
+
+
 find_trigger()
 {
   if [[ -e "/dev/disk/by-label/WP360SAVE" ]] ; then
@@ -31,59 +78,104 @@ find_trigger()
   return 0
 }
 
+
 wp360_save()
 {
   # Return codes:
   # 1: wrong argument (how?)
-  # 2: couldn't create or mount target fs for image storage
-  # 3: couldn't move previous image, or remove even older image
-  # 4: couldn't add cmdline argument to reexpand the filesystem
-  # 5: fsck couldn't run, fsck couldn't fix, or resize2fs failed
-  # 6: couldn't read mmcblk0, or couldn't write the archive on target fs
+  # 2: couldn't create or mount target fs for image storage (corrupted drive/flash?)
+  # 3: couldn't move previous image, or remove even older image (corrupted drive/flash?)
+  # 4: couldn't add cmdline argument to reexpand the filesystem (corrupted flash?)
+  # 5: fsck couldn't run, fsck couldn't fix, or resize2fs failed (corrupted flash / root filesystem?)
+  # 6: couldn't read mmcblk0, or couldn't write the archive on target fs (image is bigger than the free space available?)
+  
+  shutdown_guard
   case "$1" in
     internal)
       TARGET=/dev/disk/by-label/WP360IntRecovery
-      if [[ ! -e "$TARGET" ]] ; then
+      if ! [[ -e "$TARGET" ]] ; then
         # Should necessarily be /dev/mmcblk0p4
-        mke2fs -t ext4 -L "WP360IntRecovery" || exit 2
+        TARGET=/dev/mmcblk0p4
+        mke2fs -q -t ext4 -L "WP360IntRecovery" $TARGET || return 2
       fi
       ;;
     external)
       TARGET=/dev/disk/by-label/WP360SAVE
       ;;
     *)
-      exit 1
+      return 1
       ;;
   esac
 
   mkdir /mnt /mnt/target /mnt/boot
   
-  mount "$TARGET" /mnt/target || exit 2
+  mount "$TARGET" /mnt/target || return 2
   
   if [[ -e "/mnt/target/WP360_${MAC_ADDRESS}.img.zst" ]] ; then
     if [[ -e "/mnt/target/WP360_${MAC_ADDRESS}.old.img.zst" ]] ; then
-      rm "/mnt/target/WP360_${MAC_ADDRESS}.old.img.zst" || exit 3
+      rm "/mnt/target/WP360_${MAC_ADDRESS}.old.img.zst" || return 3
     fi
-    mv "/mnt/target/WP360_${MAC_ADDRESS}.img.zst" "/mnt/target/WP360_${MAC_ADDRESS}.old.img.zst" || exit 3
+    mv "/mnt/target/WP360_${MAC_ADDRESS}.img.zst" "/mnt/target/WP360_${MAC_ADDRESS}.old.img.zst" || return 3
   fi
   
-  mount /dev/disk/by-label/bootfs /mnt/boot || exit 4
-  sed -i 's/$/ resize-part-on-boot/' /mnt/boot/cmdline.txt || exit 4
+  mount /dev/disk/by-label/bootfs /mnt/boot || return 4
+  sed -i 's/$/ resize-fs-on-boot/' /mnt/boot/cmdline.txt || return 4
+  case "$1" in
+    internal)
+      sed -i 's/wp360-factory-backup//' /mnt/boot/cmdline.txt || return 4
+      ;;
+  esac
   sync
-  umount /mnt/boot || exit 4
+  umount /mnt/boot || return 4
 
   e2fsck -f /dev/disk/by-label/rootfs
-  [[ $? -lt 4 ]] || exit 5
-  resize2fs -f -M /dev/disk/by-label/rootfs || exit 5
+  [[ $? -lt 4 ]] || return 5
+  resize2fs -f -M /dev/disk/by-label/rootfs || return 5
   ROOT_PART_START=$(parted /dev/mmcblk0 unit B p | awk '/^ 2/ {print substr($3, 1, length($3)-1)}')
   ROOT_FS_SIZE=$(dumpe2fs -h /dev/disk/by-label/rootfs |& awk -F: '/Block count/{count=$2} /Block size/{size=$2} END{print count*size}')
   IMG_SIZE_COUNT=$(( (ROOT_PART_START + ROOT_FS_SIZE + BS * 10) / BS ))
-  dd if=/dev/mmcblk0 bs=$BS count=$IMG_SIZE_COUNT | zstd -$ZSTD_COMP_LEVEL -o /mnt/target/WP360_${MAC_ADDRESS}.img.zst || exit 6
+  dd if=/dev/mmcblk0 bs=$BS count=$IMG_SIZE_COUNT | zstd -$ZSTD_COMP_LEVEL -o /mnt/target/WP360_${MAC_ADDRESS}.img.zst || return 6
   sync
   umount /mnt/target
+  return 0
 }
 
-# TODO: start blinking 0.5hz 50%dc
+
+wp360_restore()
+{
+  # Return codes:
+  # 1: wrong argument (how?)
+  # 2: couldn't mount the target filesystem (internal restore without a proper internal recovery partition?)
+  # 3: no image to restore (was it ever created / is it an image for a different device?)
+  # 6: couldn't read the image, image is corrupted, or couldn't write the image (broken flash/pendrive?)
+
+  shutdown_guard
+  case "$1" in
+    internal)
+      TARGET=/dev/disk/by-label/WP360IntRecovery
+      ;;
+    external)
+      TARGET=/dev/disk/by-label/WP360RECV
+      ;;
+    *)
+      return 1
+      ;;
+  esac
+  mkdir /mnt /mnt/target
+
+  mount "$TARGET" /mnt/target || return 2
+
+  [[ -e "/mnt/target/WP360_${MAC_ADDRESS}.img.zst" ]] || return 3
+
+  zstd -k -d "/mnt/target/WP360_${MAC_ADDRESS}.img.zst" | dd of=/dev/mmcblk0 bs=$BS oflag=dsync conv=sparse || return 6
+  sync
+  umount /mnt/target
+  return 0
+}
+
+
+blink_led 0 &
+pid=$!
 case "$(find_trigger)" in
   save)
     wp360_save external
@@ -98,7 +190,32 @@ case "$(find_trigger)" in
     wp360_restore internal
     ;;
   *)
+    kill $pid
+    set_run_led 1
     exit 0
     ;; 
 esac
-# TODO: blink error code or light up, then hang forever
+
+ret=$?
+kill $pid
+set_run_led 1
+
+sleep 1
+case $ret in
+  0)
+    while true
+    do
+      set_run_led 0
+      sleep 1
+      set_run_led 1
+      sleep 0.2
+    done
+    ;;
+  1|2|3|4|5|6|7|8|9)
+    blink_led $ret
+    ;;
+  *)
+    sleep 86400
+    poweroff -f
+    ;;
+esac
